Yearly copyright update
Ensembl/ensembl-io pull request #118
Opened 2021-01-06 16:53 UTC by nwillhoft

## Description

Yearly copyright update to include the new year.

## Use case

N/A

## Benefits

N/A

## Possible Drawbacks

N/A

## Testing

_Have you added/modified unit tests to test the changes?_

N/A

_If so, do the tests pass/fail?_

N/A.
The tests have been run and all pass in the file: `ensembl/modules/t/housekeeping_apache2.t` 

_Have you run the entire test suite and no regression was detected?_

2021-01-07 10:24 UTC, ens-bwalts requested changes
`modules/Bio/EnsEMBL/IO/Object/Metadata.pm` got missed - this one never got the EMBL-EBI only copyright notice added back in 2016.

2021-01-07 10:38 UTC, nwillhoft commented
> `modules/Bio/EnsEMBL/IO/Object/Metadata.pm` got missed - this one never got the EMBL-EBI only copyright notice added back in 2016.

Thanks @bwalts. I've copied the updated EMBL-EBI copyright notice into this file and pushed the changes.

2021-01-07 12:22 UTC, mira13 approved these changes
Looks fine, yearly copyright update

2021-01-21 12:02 UTC, ens-bwalts approved these changes
Looks complete now

2021-01-21 12:13 UTC, merged