Feature/bcf location
Ensembl/ensembl-io pull request #119
Opened 2021-01-25 12:47 UTC by mira13

web team requested following function for ensembl-io:
new function, that loads BCF using not current directory( not enough permissions to write there), but temporary directory passed as an argument

here is an issue: https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3645?filter=-1

Unit tests are provided

2021-01-26 10:15 UTC, nwillhoft commented
As there are a number of commits ranging back from December 2019 from various users, I just wanted to check whether this was intended for this pull request?

2021-01-26 10:22 UTC, mira13 commented
@nwillhoft thanks for spotiing it! wrong base was changed.

2021-01-26 10:51 UTC, nwillhoft reviewed
A new subroutine has been added to the `BCF.pm` file that opens a BCF file using a user-provided directory path. Does this new `open_with_location` subroutine get called anywhere in `BCF.pm`?

Tests have been added to check that a test file can be opened from the correct directory, by changing to a different path immediately before attempting to open the test file, which tests that the `open` function can change directories where necessary. Please could you explain how the new functionality of `open_with_location` gets called and tested?

2021-02-02 11:06 UTC, mira13 commented
1. This new function is not called from ensembl-io, it is for external usage of web team
2.  We change path just before test, to the location that cannot be accessed without root priveleges. Then we test that in this conditions we can still load bcf, if we point temporary directory where we have permissions to write.

2021-02-02 11:55 UTC, nwillhoft requested changes
Thanks for explaining the usage of the new subroutine and how it is now tested. Changes look good based on this. Build checks however are currently failing, please could this be looked into.

2021-02-02 12:05 UTC, nwillhoft approved these changes
Approving this PR because build is failing for reasons not related to this PR (i.e. due to unexpected warnings relating to software and database version mismatches, which are currently being patched).

2021-02-03 11:08 UTC, merged